name: 'Github Action Soti Apk Uploader'
description: 'Greet someone and record the time'
inputs:
  soti-api-url:
    description: 'Soti api url'
    required: true
  workspace:
    description: 'Github workspace'
    required: true
  apk-name:
    description: 'Apk name'
    required: true
  soti-api-key:
    description: 'Soti api key'
    required: true
  soti-api-secret:
    description: 'Soti api secret'
    required: true
  soti-username:
    description: 'Soti username'
    required: true
  soti-password:
    description: 'Soti password'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
